version: '3.8'
services:
  backend:
    container_name: the_eye_backend
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    environment:
      - DJANGO_SETTINGS_MODULE=the_eye.settings
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    ports:
      # localhost:remote
      - 8000:8000
    volumes:
      # Creating bound between root directory and directory from remote
      - .:/app
    depends_on:
      - db
      - redis
  
  celery:
    build: .
    command: celery -A the_eye worker -l INFO
    volumes:
      # Creating bound between root directory and directory from remote
      - .:/app
    depends_on:
      - backend
      - redis
  
  db:
    image: postgres:13-alpine
    container_name: the_eye_db
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
  
  redis:
    image: redis:alpine
